### ISSUE TITLE
Incorporate codetective

### ISSUE THREAD

**Issue by MariasStory** [bee-san/pyWhat#118]
This one seems to be an older repo:
https://github.com/blackthorne/Codetective

**Comment by piatrashkakanstantinass** [comment]
Hi there 👋! It seems that you are looking for [name-that-hash](https://github.com/HashPals/Name-That-Hash). PyWhat used it in the past; however, currently, hashes are not supported by what.

**Comment by MariasStory** [comment]
Thank you.
Closing the issue
