### ISSUE TITLE
When in bug bounty mode, do not print "Nothing found!"

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#155]
By only printing when something is found, you can watch the output of the process and alert on successes.

**Comment by Alireza-Sampour** [comment]
I would like to work on this, just to make sure: the script should not print "Not found!" when bug bounty mode is on? it is right?

**Comment by bee-san** [comment]
That's correct, it should _only_ print when it finds something :)

**Comment by Alireza-Sampour** [comment]
I think it can be done with add another condition in `print_raw` and `pretty_print` to check if bug_bounty_mode is not set then it can print "Nothing found!".
If this assigns to me would be great and I will send a pull request for it.

**Comment by Alireza-Sampour** [comment]
I created a pull request, hope everything's fine.
