### ISSUE TITLE
Wrong detection in bug bounty mode

### ISSUE THREAD

**Issue by signorrayan** [bee-san/pyWhat#164]
when we clone a github repository, a `.git` directory will be created and inside that, we will have some sub directories such as:

- `.git/refs/heads/`
- `.git/logs/`
- `.git/logs/refs/heads/`
and inside these sub directories, we have some files, for example, inside  `.git/refs/heads/master` file, we have a hash for head branch, and then the BugBounty feature, detects these hashes as `Amazon Web Services Secret Access Key` .

testing one of the matched results:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/tYyXY6p/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/fnBmVTT"><img src="https://i.ibb.co/9VzRmdd/2.png" alt="2" border="0"></a>

**Comment by piatrashkakanstantinass** [comment]
That is because of false positives, and we cannot do much to change that (we already have a filtration system to exclude some matches). [Name-That-Hash](https://github.com/HashPals/Name-That-Hash) can be used to identify hashes.
