### ISSUE TITLE
Lat / Long matches incorrectly

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#197]
```
$ poetry run pywhat acb6d73d95a10d30aef9894603e90963   

Matched on: e90963
Name: Latitude & Longitude Coordinates
Link:  https://www.google.com/maps/place/e90963
```

Bug found in #196

**Comment by Vipul-Bajaj** [comment]
Can you please explain more on this issue?

**Comment by bee-san** [comment]
> Can you please explain more on this issue?

Sure! `e90963` is not valid latitude / longitude coordinates and it shouldn't match :(

**Comment by Saacket** [comment]
plz explain

**Comment by nodtem66** [comment]
I propose this new one: https://regex101.com/r/WrINyr/1

The old RegEx consists of three patterns:
1. **Full expression with symbols and prefix N/W/S/E , e.g. N 32° 53.733 W 096° 48.358**
`(?:(?:N|W|S|E)\\s?\\d+\\s?\\u00B0?\\s?\\d+\\.?\\d*\\s?\\'?\\s?\\d*\\.?\\,?\\d*?\"?\\s?){1,2}`
2. **Full expression with symbols and subfix N/W/S/E, e.g. 13°55'24.3"N 101°20'30.1"E**
`(?:\\d+\\s?\\u00B0\\s?\\d+\\s?\\'\\s?\\d+\\.?\\,?\\d{0,}?\"\\s?(?:N|W|S|E)\\s?){1,2}`
3. **Two decimal numbers without symbols and prefixs, e.g.  52.6169586, -1.9779857** 
`(?:[-+]?(?:[0-8]?\\d+\\.\\d{4,}|90(?:\\.0+)?),\\s*[-+]?(?:180(?:\\.0+)?|(?:(?:1[0-7]\\d)|(?:[1-9]?\\d))(?:\\.\\d+)?))`
https://github.com/bee-san/pyWhat/blob/6162aceac5b9b68e2bd8f8af56cb94f2eab4a69c/pywhat/Data/regex.json#L1480

The first pattern slightly differs from the second pattern in the symbol matchings
- `\\u00B0?` and `\\u00B0`
- `\\'?` and `\\'`
- `\"?` and `\"`
This causes the RegEx matching of `e26`, `e90963`, and so on.

I've observed that there is nothing like `N 52.6169586, W -1.9779857`; only N 32° 53.733 W 096° 48.358, and 52.6169586, -1.9779857 are valid.

Then these symbol matching should've been changed to the strict matching of `\\u00B0`, `\\'`, and `\"` or the flexible matching of  `\\u00B0`, `\\'?`, and `\"?`.

If it looks fine, I'll make a patch.
Thanks
