### ISSUE TITLE
Amazon Web Services EC2 Instance identifier matches incorrectly

### ISSUE THREAD

**Issue by SkeletalDemise** [bee-san/pyWhat#200]
```
$ poetry run pywhat "j-I"
Matched on: j-I
Name: Amazon Web Services EC2 Instance identifier
```
It's way too broad. If it can't be less broad then make the rarity `0`.

**Comment by piatrashkakanstantinass** [comment]
> Looking in the `regex.json` seems that the rule for this Identifier is `(?i)^(\\b[a-z]+-[a-z0-9]+)$`, which doesn't match with the valid example `i-1234567890abcdef0`
> 
> How is this regex used ?

Well, the regex is messed up.
