### ISSUE TITLE
[Proposal] parse timestamps

### ISSUE THREAD

**Issue by whyboris** [bee-san/pyWhat#234]
Feels like an easy thing to add: 

parse a *timestamp* like `1637093119.558717` or `1637093119`

which would convert to `November 16, 2021 8:05:19 PM`

Currently `what` thinks it's a "phone number" or "American social security number" 🤷  

Cheers  😎

**Comment by piatrashkakanstantinass** [comment]
We have an issue for this: https://github.com/bee-san/pyWhat/issues/115

**Comment by whyboris** [comment]
@piatrashkakanstantinass -- seems rather unrelated. Your issue is about going on the internet to check the validity of a YouTube video.

The feature I propose is as simple as checking whether the input is a number, whether it's of a certain length, and if so, parsing it as a date 👌

**Comment by piatrashkakanstantinass** [comment]
My issue is about adding non-regex checkers and you provided a great situation where it could be useful. Pinging urls is just an example.

**Comment by bee-san** [comment]
I don't think parsing == checking, but I agree. However! I am not sure if this should be done at print time or API time, because I think this could genuinely be useful for people using the API 🤔

**Comment by piatrashkakanstantinass** [comment]
> I don't think parsing == checking, but I agree. However! I am not sure if this should be done at print time or API time, because I think this could genuinely be useful for people using the API 🤔

I think that API should return the same output as CLI, so at API time. I imagine checkers being like a filtration function: it gets a match object and can modify it. If the function returns None, then match will not appear in the output.

@whyboris I will update my issue with better naming and examples and will close this one since this is a duplicate.
