### ISSUE TITLE
Have an argument which returns JSON in `what`

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#24]
This is for like an open API that lets people use it!

**Comment by RackReaver** [comment]
Is this something that you just want added to `pywhat/what.py:main` as an argument? Do you still want it returned to the terminal or written to a file?

**Comment by bee-san** [comment]
It should print to the terminal with no other output so it can be easily parsed into a file like `pywhat 'hello' --json > output.json` :)

**Comment by RackReaver** [comment]
Sounds good, I will work on this and get it done. Assign it to me please.

**Comment by RackReaver** [comment]
Not sure if you wanted to see all the values so I removed `Regex, plural_name, Tags and Rarity`. I mimicked the values provided in the stdout table and removed the other values as seen on line 106 in `pywhat/printer.py`. 

Let me know if you want them included and I can add them back.

**Comment by bee-san** [comment]
Yes, please return all of the details! :) <3

**Comment by RackReaver** [comment]
> Yes, please return all of the details! :) <3

Done.
