### ISSUE TITLE
API keys Regex

### ISSUE THREAD

**Issue by Caesurus** [bee-san/pyWhat#42]
Love the tool BTW,

https://www.redpacketsecurity.com/secretfinder-a-python-script-for-find-sensitive-data-apikeys-accesstoken-jwt-and-search-anything-on-javascript-files/?utm_source=rss&utm_medium=rss&utm_campaign=secretfinder-a-python-script-for-find-sensitive-data-apikeys-accesstoken-jwt-and-search-anything-on-javascript-files

This has some apikey regex's which would be useful.

**Comment by bee-san** [comment]
Thank you so much! We can add API keys for sure :-)

**Comment by bee-san** [comment]
GitHub link: https://github.com/m4ll0k/SecretFinder
