### ISSUE TITLE
Using a folder path as input

### ISSUE THREAD

**Issue by Jayy001** [bee-san/pyWhat#43]
* What is a great tool for identifying anything, but it also supports file input such as .pcap
* Sometimes, we have loads of of files we want to scan for but it will take a long time to manually input each file into what

This is where the "folder" input comes in, give it a folder path and for each file / folder in there it will identify it

**Comment by zarszz** [comment]
it look interesting, it like give folder/directory as input and application scan files in entire folder right ?
