### ISSUE TITLE
Not working README example

### ISSUE THREAD

**Issue by piatrashkakanstantinass** [bee-san/pyWhat#55]
As README says:

>Imagine this: You come across some mysterious text 🧙‍♂️ `5f4dcc3b5aa765d61d8327deb882cf99` and you wonder what it is. What do you do?
Well, with `what` all you have to do is ask `what "5f4dcc3b5aa765d61d8327deb882cf99"` and `what` will tell you!

But 'what' does not tell me! It does not find anything.
Therefore, `5f4dcc3b5aa765d61d8327deb882cf99` should be replaced with something else.

**Comment by thewilloftheshadow** [comment]
Hey hey! I'd be happy to record some gifs/pngs if you'd like and help to reorganize the README @bee-san

**Comment by bee-san** [comment]
> Hey hey! I'd be happy to record some gifs/pngs if you'd like and help to reorganize the README @bee-san

Oh sure! I'd love that :-) We use asciinema to record, and asciinema2gif to convert it to a gif :-) https://dstein64.github.io/gifcast/

If you have anything else that's easier for gifs, feel free to use that! :D
