### ISSUE TITLE
Scan webpage support

### ISSUE THREAD

**Issue by piatrashkakanstantinass** [bee-san/pyWhat#66]
It would be great if pywhat could identify data from a webpage.

**Comment by bee-san** [comment]
Can you show an expected input and output? I imagine a page like bbc.co.uk would have ** a lot** of data?

**Comment by piatrashkakanstantinass** [comment]
I have been thinking about using what to scrape the web and identify data; however, now I see that it is much better to use the specialized library for that in conjunction with pywhat.
