### ISSUE TITLE
Support checksums/hashes

### ISSUE THREAD

**Issue by danielskowronski** [bee-san/pyWhat#83]
One thing I immediately thought about when I saw this was "wow, now I can quickly identify unknown checksums offline" and then `Nothing found!` happened. Would be nice to support range of formats like https://www.onlinehashcrack.com/hash-identification.php

**Comment by bee-san** [comment]
Hey @danielskowronski  !! I have another tool for you, https://github.com/HashPals/Name-That-Hash which does identify hashes!

I _was_ going to implement it into `PyWhat`, but I do not believe it'll be useful perhaps? As hashes need to be de-hashed for them to have any real value?

I'll have a lil debate over this with the team.
