### ISSUE TITLE
Identify PGP keys?

### ISSUE THREAD

**Issue by seisvelas** [bee-san/pyWhat#84]
Not sure if this would be an appropriate functionality for this project. It doesn't seem to currently be supported, when I try running pywhat against a file containing a PGP public key, it says nothing found.

if this would be appropriate, I'd be happy to put up a PR implementing it :)

**Comment by bee-san** [comment]
Yup!!! Problem is, `Identify Anything` only works well with the network effect when we have a large enough database 😅  We're getting there!

Sure, open a PR if you can! 

We currently use regex for everything (well, almost!), you can read the wiki here:
https://github.com/bee-san/pyWhat/wiki/Adding-your-own-Regex
