### ISSUE TITLE
Identify discord tokens

### ISSUE THREAD

**Issue by Switch1024** [bee-san/pyWhat#93]
Here is la regex :
```[N]([a-zA-Z0-9]{23})\.([a-zA-Z0-9]{6})\.([a-zA-Z0-9]{27})```

**Comment by bee-san** [comment]
Thanks! Got an example? :)

**Comment by RackReaver** [comment]
This regex only works on some, pastebin has a bunch of examples:
https://pastebin.com/T41ej5hq

**Comment by Switch1024** [comment]
> This regex only works on some, pastebin has a bunch of examples:
> https://pastebin.com/T41ej5hq

This regex works with most tokens unless Discord switches they structure of the tokens. There are some exceptions yes
