### ISSUE TITLE
Example on README.md doesn't work ?

### ISSUE THREAD

**Issue by CaptainCaptcha** [bee-san/pyWhat#97]
![2021-06-21 22_03_33-Window](https://user-images.githubusercontent.com/86262252/122814212-8f13a700-d2dc-11eb-8805-3a5970562eb1.png)
![2021-06-21 22_03_56-Window](https://user-images.githubusercontent.com/86262252/122814285-a6529480-d2dc-11eb-8da8-2a34dfb5d234.png)

**Comment by amadejpapez** [comment]
Hi! That is an MD5 hash and it isn't identified by PyWhat as support for hashes is currently disabled.

We are working on updating the examples and gifs in the README! :D If you have a hash and you want to know what type it is, you can use another awesome tool [Name-That-Hash](https://github.com/HashPals/Name-That-Hash). :)

**Comment by KorayPlatin** [comment]
@amadejpapez Thanks, I was just confused.

**Comment by amadejpapez** [comment]
Yeah no problem! We really need to change it 😄
